- name: Install step client
  include_role:
    name: maxhoesel.smallstep.step_client
  vars:
    stepclient_ca_servers: []

# These pipes squelch the "command not found" error message if the binary isn't installed yet.
# Instead, they return "", which we simply use as our version string.
# Not the cleanest solution, but it's simple and works well.
- name: Get current step-ca version
  shell: "{{ stepca_executable_path }}/step-ca version | cut -d' ' -f 2 | cut -d'/' -f 2 | awk 'FNR == 1'" # noqa 306
  changed_when: no
  register: stepca_current_version

- block:
  - name: Get latest step-ca release information
    uri:
      url: https://api.github.com/repos/smallstep/certificates/releases/latest
      body_format: json
      return_content: yes
    register: stepca_latest_release
    delegate_to: localhost
    run_once: yes
    retries: 3
    delay: 3
  - name: Set release tag
    set_fact:
      stepca_version: '{{ (stepca_latest_release.json.tag_name)[1:] }}'
  when: stepca_version == 'latest'

- name: Insatll step-ca
  include: 'install_{{ ansible_os_family }}.yml'
