---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # Note on containers:
  # - We use the images provided by geerlingguy, as they provide out-of-the-box
  #   support for Ansible and systemd (needed to test service management).
  # - The containers run as privileged containers so that we can
  #   use systemd functionality. This *should* be possible with unpriliged
  #   containers as well, but is quite the headache.
  # - All containers are connected to a custom "smallstep" network to
  #   allow for name resolution
  - name: server-ubuntu-20
    image: "geerlingguy/docker-ubuntu2004-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
    networks:
      - name: smallstep
  - name: server-ubuntu-18
    image: "geerlingguy/docker-ubuntu1804-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
    networks:
      - name: smallstep
  - name: server-debian-10
    image: "geerlingguy/docker-debian10-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
    networks:
      - name: smallstep
  - name: server-centos-8
    image: "geerlingguy/docker-centos8-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
    networks:
      - name: smallstep


  - name: client-ubuntu-20
    image: "geerlingguy/docker-ubuntu2004-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
    networks:
      - name: smallstep
  - name: client-ubuntu-18
    image: "geerlingguy/docker-ubuntu1804-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
    networks:
      - name: smallstep
  - name: client-debian-10
    image: "geerlingguy/docker-debian10-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
    networks:
      - name: smallstep
  - name: client-centos-8
    image: "geerlingguy/docker-centos8-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
    networks:
      - name: smallstep
provisioner:
  name: ansible
  options:
    vvv: ${TESTENV_VERBOSE:-false}
  config_options:
    ssh_connection:
      pipelining: yes
  env:
    ANSIBLE_KEEP_REMOTE_FILES: ${TESTENV_KEEP_REMOTE:-false}
    ANSIBLE_COLLECTIONS_PATH: ${TESTENV_COLLECTIONS:-~/.ansible/collections:/usr/share/ansible/collections}
  inventory:
    hosts:
      all:
        vars:
          testing_password: molecule-test
        children:
          servers:
            vars:
              stepca_name: Molecule-Test
              stepca_dns_name: localhost
              stepca_root_password: '{{ testing_password }}'
              stepca_intermediate_password: '{{ testing_password }}'
              stepca_root_cert: '{{ lookup("file", "files/molecule_ca_crt") }}'
              stepca_root_key: '{{ lookup("file", "files/molecule_ca_key") }}'
            hosts:
              server-ubuntu-20:
              server-ubuntu-18:
              server-debian-10:
              server-centos-8:
          clients:
            vars:
              # TODO: Generate this list automaticallyW
              stepclient_ca_servers:
                - url: 'https://server-ubuntu-20:443'
                  fp: 93edf189e74fa44e9dfe74fc18d4cfd5d93b09cc210d2352171d5ea9dd70669c
                - url: 'https://server-ubuntu-18:443'
                  fp: 93edf189e74fa44e9dfe74fc18d4cfd5d93b09cc210d2352171d5ea9dd70669c
                - url: 'https://server-debian-10:443'
                  fp: 93edf189e74fa44e9dfe74fc18d4cfd5d93b09cc210d2352171d5ea9dd70669c
                - url: 'https://server-centos-8:443'
                  fp: 93edf189e74fa44e9dfe74fc18d4cfd5d93b09cc210d2352171d5ea9dd70669c
            hosts:
              client-ubuntu-20:
              client-ubuntu-18:
              client-debian-10:
              client-centos-8:
verifier:
  name: ansible
